title: My personal blog - Andreas Evers
email: krosan@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://andreasevers.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Author settings
author: Andreas Evers
author-pic: andreas-face.jpg
about-author: My name is Andreas Evers. I'm a principal Java consultant @Ordina. Passionate about the Spring ecosystem, microservices, REST, clean code, ... Avid open source enthusiast & Spring contributor.

# Contact links
email: krosan@gmail.com
phone: +32476363308
website: andreasevers.github.io
linkedin: eversandreas
github: andreasevers
twitter: '@andreasevers'
speakerdeck: andreasevers

# Newsletter
mailchimp: # Add your MailChimp form identifier.

# Disqus
discus_identifier: andreasevers-github-io

# Tracker
analytics: # Google Analytics

# Paginate
paginate: 6
paginate_path: /page:num/

# Build settings
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
